# -*- coding: utf-8 -*-
"""Simulación Articulo Mecánica Estadística.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M0zC6KjtJUkDI26C9YHmFYBQyw_53pWY
"""

import numpy as np
import matplotlib.pyplot as plt

# =====================================================================
# BLOQUE 1: CONSTANTES FÍSICAS Y PARAMETRIZACIÓN DEL BGO
# =====================================================================
E_gamma  = 511000     # Energía del rayo gamma incidente (eV)
W_scint  = 114        # eV por fotón (LY ~ 8,800 ph/MeV a T=300 K)

# MODELO MOTT-SEITZ EFECTIVO (Calibración empírica agregada)
# En el BGO, el apagamiento no sigue un único canal de Arrhenius puro de red (Melcher, 1985).
# Por tanto, DELTA_E y A_FACTOR operan como parámetros efectivos acoplados
# para reproducir el gradiente de deriva térmica del rendimiento luminoso macroscópico
# reportado experimentalmente (IAEA, 2009) en el rango clínico (250-320 K).
DELTA_E  = 0.12       # Energía de activación efectiva (eV)
A_FACTOR = 10.0       # Factor de frecuencia efectivo adimensional (Calibrado)

k_B      = 8.617e-5   # Constante de Boltzmann (eV/K)
N_eventos = 1000000
temperaturas = [250, 273, 300, 320]

SEED = 42
rng  = np.random.default_rng(SEED)

# =====================================================================
# BLOQUE 2: PROBABILIDAD DE PÉRDIDA NO RADIATIVA (MOTT-SEITZ)
# =====================================================================
import numpy as np

def calcular_probabilidad_perdida(T):
    if T <= 0:
        return 0
    # Término de Arrhenius competitivo
    termino_termico = A_FACTOR * np.exp(-DELTA_E / (k_B * T))
    # Eficiencia relativa frente a la atenuación fonónica clínica
    eta = 1.0 / (1.0 + termino_termico)
    return 1.0 - eta

# =====================================================================
# BLOQUE 3: MOTOR DE SIMULACIÓN MONTE CARLO
# =====================================================================
espectros_por_temperatura = {}

for T in temperaturas:
    # Calculamos la probabilidad dinámicamente según la temperatura de entrada
    probabilidad_perdida = calcular_probabilidad_perdida(T)
    fotones_detectados_en_eventos = []

    # Optimizamos calculando N_ideal fuera del bucle interno
    N_ideal = E_gamma / W_scint

    for evento in range(N_eventos):
        N_generado = np.random.poisson(N_ideal)

        # Filtro binomial regido por la probabilidad termodinámica de Mott-Seitz
        fotones_perdidos = np.random.binomial(N_generado, probabilidad_perdida)
        fotones_finales = N_generado - fotones_perdidos
        fotones_detectados_en_eventos.append(fotones_finales)

    espectros_por_temperatura[T] = np.array(fotones_detectados_en_eventos)

# =====================================================================
# BLOQUE 4: ANÁLISIS, INCERTIDUMBRES Y VISUALIZACIÓN
# =====================================================================
plt.figure(figsize=(10, 6))
colores = {250: '#1f77b4', 273: '#2ca02c', 300: '#ff7f0e', 320: '#d62728'}

print(f"{'T (K)':<8} | {'Centroide (keV)':<25} | {'Resolución R (%)':<25} | {'Error Relativo (ΔR/R)'}")
print("-" * 90)

for T in temperaturas:
    datos      = espectros_por_temperatura[T]
    energia_kev = (datos * W_scint) / 1000

    # ------------------------------------------------------------------
    # ESTIMADORES DE PRIMER Y SEGUNDO MOMENTO
    # ------------------------------------------------------------------
    centroide  = np.mean(energia_kev)
    desviacion = np.std(energia_kev, ddof=1)   # desviación típica muestral
    fwhm       = 2.355 * desviacion
    resolucion = (fwhm / centroide) * 100

    # ------------------------------------------------------------------
    # PROPAGACIÓN ANALÍTICA DE INCERTIDUMBRES (método de momentos)
    # Error estándar del centroide: Δμ = s / sqrt(N)
    # Error estándar de s:          Δs = s / sqrt(2N)   [dist. gaussiana, N>>1]
    # Propagación en cuadratura:    ΔR/R = sqrt((Δfwhm/fwhm)² + (Δμ/μ)²)
    # ------------------------------------------------------------------
    delta_centroide  = desviacion / np.sqrt(N_eventos)
    delta_desviacion = desviacion / np.sqrt(2 * N_eventos)
    delta_fwhm       = 2.355 * delta_desviacion

    delta_resolucion = resolucion * np.sqrt(
        (delta_fwhm      / fwhm     ) ** 2 +
        (delta_centroide / centroide) ** 2
    )
    error_relativo_R = delta_resolucion / resolucion

    # ------------------------------------------------------------------
    # SALIDA EN CONSOLA
    # ------------------------------------------------------------------
    print(f"{T:<8} | "
          f"{centroide:.2f} +/- {delta_centroide:.2e}      | "
          f"{resolucion:.2f} +/- {delta_resolucion:.2e}      | "
          f"{error_relativo_R:.2e}")

    # ------------------------------------------------------------------
    # ETIQUETA DE LA FIGURA
    # ------------------------------------------------------------------
    etiqueta = (f"T = {T} K | "
                f"$R_{{\\mathrm{{int}}}}$ = {resolucion:.2f} "
                f"$\\pm$ {delta_resolucion:.3f}%")

    plt.hist(
        energia_kev,
        bins=60,
        density=True,
        histtype='step',
        linewidth=2.5,
        color=colores[T],
        label=etiqueta
    )

# ------------------------------------------------------------------
# FORMATO DE LA FIGURA 1
# ------------------------------------------------------------------
plt.xlabel('Energía Aparente (keV)', fontsize=12)
plt.ylabel('Densidad de Probabilidad',            fontsize=12)
plt.xlim(380, 530)
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend(loc='upper left', fontsize=11)
plt.tight_layout()

plt.savefig('espectro_fonones.pdf', dpi=300)
plt.show()

# =====================================================================
# BLOQUE 5 FIGURA 2: R_int (%) vs Temperatura (K) con barras de error
# =====================================================================

# Extraer valores ya calculados del bucle principal
temps       = []
resoluciones = []
errores_R   = []
centroides  = []
errores_c   = []

for T in temperaturas:
    datos       = espectros_por_temperatura[T]
    energia_kev = (datos * W_scint) / 1000

    centroide   = np.mean(energia_kev)
    desviacion  = np.std(energia_kev, ddof=1)
    fwhm        = 2.355 * desviacion
    resolucion  = (fwhm / centroide) * 100

    delta_centroide  = desviacion / np.sqrt(N_eventos)
    delta_desviacion = desviacion / np.sqrt(2 * N_eventos)
    delta_fwhm       = 2.355 * delta_desviacion
    delta_resolucion = resolucion * np.sqrt(
        (delta_fwhm      / fwhm     ) ** 2 +
        (delta_centroide / centroide) ** 2
    )

    temps.append(T)
    resoluciones.append(resolucion)
    errores_R.append(delta_resolucion)
    centroides.append(centroide)
    errores_c.append(delta_centroide)

# ------------------------------------------------------------------
# Panel doble: R_int vs T  |  Centroide vs T
# ------------------------------------------------------------------
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# --- Panel izquierdo: R_int vs T ---
ax1.errorbar(
    temps, resoluciones, yerr=errores_R,
    fmt='o-',
    color='steelblue',
    linewidth=2,
    markersize=7,
    capsize=5,
    capthick=1.5,
    elinewidth=1.5,
    label=r'$R_{\mathrm{int}}$ (ajuste de momentos)'
)

# Línea de referencia: límite de Poisson puro (sin pérdidas)
R_poisson_puro = (2.355 / np.sqrt(E_gamma / W_scint)) * 100
ax1.axhline(
    R_poisson_puro,
    color='gray',
    linestyle='--',
    linewidth=1.5,
    label=f'Límite Poisson puro ($P_{{loss}}=0$): {R_poisson_puro:.2f}%'
)

ax1.set_xlabel('Temperatura (K)', fontsize=12)
ax1.set_ylabel(r'$R_{\mathrm{int}}$ (%)', fontsize=12)
ax1.set_title(r'Resolución Intrínseca $R_{\mathrm{int}}$ vs Temperatura',
              fontsize=12, fontweight='bold')
ax1.set_xticks(temperaturas)
margen = 0.3
ax1.set_ylim(min(resoluciones) - margen, max(resoluciones) + margen)
ax1.legend(fontsize=10)
ax1.grid(True, linestyle='--', alpha=0.6)

# Anotación de variación total
delta_R_total = max(resoluciones) - min(resoluciones)
ax1.annotate(
    f'$\\Delta R_{{\\mathrm{{int}}}}$ = {delta_R_total:.2f}%',
    xy=(320, max(resoluciones)),
    xytext=(270, max(resoluciones) + 0.15),
    arrowprops=dict(arrowstyle='->', color='black'),
    fontsize=10
)

# --- Panel derecho: Centroide vs T ---
ax2.errorbar(
    temps, centroides, yerr=errores_c,
    fmt='s-',
    color='firebrick',
    linewidth=2,
    markersize=7,
    capsize=5,
    capthick=1.5,
    elinewidth=1.5,
    label='Centroide fotoeléctrico'
)

# Línea de referencia: energía nominal 511 keV
ax2.axhline(
    511,
    color='gray',
    linestyle='--',
    linewidth=1.5,
    label='Energía nominal 511 keV'
)

# Banda de ventana de aceptación PET
ax2.axhspan(440, 565, alpha=0.08, color='green',
            label='Ventana de aceptación PET (440-565 keV)')

ax2.set_xlabel('Temperatura (K)', fontsize=12)
ax2.set_ylabel('Centroide (keV)', fontsize=12)
ax2.set_title('Deriva Térmica del Centroide Fotoeléctrico',
              fontsize=12, fontweight='bold')
ax2.set_xticks(temperaturas)
ax2.legend(fontsize=10)
ax2.grid(True, linestyle='--', alpha=0.6)

# Anotación de deriva total
delta_c_total = max(centroides) - min(centroides)
ax2.annotate(
    f'$\\Delta E_{{\\mathrm{{centroide}}}}$ = {delta_c_total:.1f} keV',
    xy=(250, min(centroides)),
    xytext=(255, min(centroides) - 8),
    arrowprops=dict(arrowstyle='->', color='black'),
    fontsize=10
)

fig.suptitle(
    'Impacto Térmico sobre los Parámetros Métricos del Cristal de BGO',
    fontsize=13, fontweight='bold', y=1.02
)
fig.tight_layout()
fig.savefig('figura_metricas_vs_temperatura.pdf', dpi=300,
            bbox_inches='tight')
plt.show()